### ISSUE TITLE
Div by Zero 4D Pop Image buddy Browser_Fill line 197

### ISSUE THREAD

**Issue by PrimeAdam** [vdelachaux/4DPop-Image-Buddy#3]
This error as reported by Bertrand still present in "Latest" version I downloaded today from Git-hub dated 29 Apr 2020.

Occurs when clicking on a folder in the pictures browser which does not contain pictures

**Comment by vdelachaux** [comment]
Hi,
Can you describe how to get this error, I don't find the way to reproduce it.
Maybe the problem has already been fixed and has not been included in the final version.
Thanks

**Comment by vdelachaux** [comment]
Hi,
I just verify the code in the last version and this error is fixed.
You can find the last version of the component [here](https://github.com/vdelachaux/4DPop-Image-Buddy/releases/latest) or get the all-in-one family [here](https://github.com/vdelachaux/4DPop-Family/releases/latest).
Thanks
